-- Replace an inaccurate legacy Blackwatch article and publish factual release notes.

UPDATE content_items
SET status = 'archived', updated_at = CURRENT_TIMESTAMP
WHERE id = 'seed-blog-blackwatch-design-philosophy';

INSERT OR IGNORE INTO content_items (id, type, slug, title, status, sort_order, data_json, created_at, updated_at, published_at) VALUES
('seed-blog-blackwatch-early-alpha-release', 'blog', 'blackwatch-early-alpha-release', 'Blackwatch 0.1.0: The Early Alpha Is Live', 'published', 10,
 '{"date":"2026-09-15","category":"RELEASES","excerpt":"The first public Blackwatch build brings local process and network visibility, explainable evidence, and guarded response controls to Windows.","readTime":"4 min","content":"## A First Public Look at Blackwatch\n\nBlackwatch 0.1.0 is now available as an early-alpha build for Windows x64. It is a local monitoring tool designed to make active processes and TCP connections easier to inspect without hiding the evidence behind a single unexplained score.\n\nThe release shows live CPU, memory, process, and connection activity. Process details can include the executable path, SHA-256 hash, publisher, and signature information. Heuristic findings are presented as evidence for the user to review.\n\n## Guardrails Come First\n\nResponse controls require confirmation, and Dry-Run Mode is enabled by default. Trusted-application entries are bound to application identity rather than only a display name. Diagnostic exports redact private data where possible.\n\nBlackwatch is not an antivirus and does not replace Microsoft Defender or another reputable security product. It is an additional inspection layer, and this first build should be treated as evaluation software.\n\n## Download Options\n\nThe release includes an installer and a portable ZIP. Both are unsigned early-alpha builds, so Windows may show an Unknown publisher or SmartScreen warning. Verify the SHA-256 checksum shown on the Blackwatch page before running a downloaded file."}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('seed-blog-vault-cleaner-public-beta', 'blog', 'vault-cleaner-public-beta', 'Vault Cleaner 1.0.0 Enters Public Beta', 'published', 11,
 '{"date":"2026-09-15","category":"RELEASES","excerpt":"A Windows cleanup and disk-analysis tool built around exact previews, protected-path validation, and recoverable deletion.","readTime":"4 min","content":"## Cleanup You Can Review\n\nSoftcurse Vault Cleaner 1.0.0 is now available as a public beta for Windows 10 and 11. The central rule is simple: cleanup should be deliberate. The application previews exact targets before removal and rejects protected paths, unsafe roots, junctions, and mount points.\n\nSupported filesystem cleanup is sent to the Recycle Bin so mistakes remain recoverable. The app runs as a standard user and requests elevation only for optional Windows component maintenance.\n\n## More Than Temporary Files\n\nVault Cleaner can analyze drives or selected folders, identify unusually large files, and find duplicates. HTML storage reports make the results easier to review outside the application.\n\nThe beta installer is hosted on GitHub Releases. It is not digitally signed yet, so Windows may display an Unknown publisher or SmartScreen warning. Compare the downloaded file with the SHA-256 checksum published on the product page before installation."}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('seed-blog-media-lab-ai-v1-release', 'blog', 'media-lab-ai-v1-release', 'Softcurse Media Lab AI 1.0 Is Available', 'published', 12,
 '{"date":"2026-09-15","category":"RELEASES","excerpt":"The Windows media workspace combines image retouching, video cleanup, and audio/video conversion, with optional generative tools.","readTime":"4 min","content":"## One Workspace for Practical Media Tasks\n\nSoftcurse Media Lab AI 1.0 is available for Windows x64. Its core is a local media editor for image retouching, object and watermark removal, background work, video cleanup, and audio/video conversion.\n\nThe desktop application is built with WPF and .NET 8. ONNX Runtime, DirectML, OpenCV, and FFmpeg provide the processing foundation. Despite the name, generative AI is optional rather than the product category or a requirement for the main editing workflow.\n\n## Local Core, Optional Extensions\n\nThe editor, Toolkit Lab, local processing tools, and bundled FFmpeg workflow work without an external AI service. Users who want generative features can connect a trusted Stable Diffusion WebUI-compatible API.\n\nThe first release date is July 12, 2025. The current Windows installer and its SHA-256 checksum are available from the Media Lab product page."}', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT OR IGNORE INTO content_revisions (content_id, revision, action, data_json, created_by, created_at)
SELECT id, 1, 'publish_release_post', data_json, 'system-editorial', CURRENT_TIMESTAMP
FROM content_items
WHERE id IN ('seed-blog-blackwatch-early-alpha-release', 'seed-blog-vault-cleaner-public-beta', 'seed-blog-media-lab-ai-v1-release');

INSERT INTO audit_log (actor, action, entity_type, entity_id, metadata_json, created_at)
VALUES ('system-editorial', 'publish_release_posts', 'blog', NULL, '{"count":3,"archivedInaccuratePost":"seed-blog-blackwatch-design-philosophy"}', CURRENT_TIMESTAMP);
